name: Lint

on:
  workflow_call:

concurrency:
  group: Lint-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: ðŸ›¡ Lint
    runs-on: 2core-4gb-amd
    timeout-minutes: 15
    env:
      PRE_COMMIT_HOME: "${{ github.workspace }}/.cache/pre-commit"
      RUFF_CACHE_DIR: "${{ github.workspace }}/.cache/ruff"
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
      - name: Set up Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@v5.6.0
        with:
          python-version: '3.13'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Load cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # pin@v4.2.3
        id: cache
        with:
          path: |
            ${{ env.PRE_COMMIT_HOME }}
            ${{ env.RUFF_CACHE_DIR }}
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Lint
        run: pre-commit run --show-diff-on-failure --color=always --all-files -v
